using System.Windows.Controls;
using Telerik.Windows.Controls;
using Telerik.Windows.Controls.Data.DataForm;
using System.Windows.Data;
using System.Windows;

namespace Telerik.Windows.Examples.DataForm.CustomizeAutoGeneratedFields
{
	public partial class Example : UserControl
	{
		public Example()
		{
			InitializeComponent();

            DataContext = new EmployeeDataContext();
		}

        private void RadDataForm_AutoGeneratingField(object sender, AutoGeneratingFieldEventArgs e)
        {
            if (e.PropertyName == "FirstName")
            {
                e.Cancel = true;
            }
            else if (e.PropertyName == "LastName")
            {
                e.DataField.Label = "Last Name";
            }           
            else if (e.PropertyName == "StartingDate")
            {
                e.DataField.ContentTemplate = this.Resources["datePickerTemplate"] as DataTemplate;
                e.DataField.Label = ((string)e.DataField.Label).Replace("StartingDate", "Starting Date");
            }          
        }
	}
}